myfinance-web-dotnet/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myfinance-web-dotnet/Models/PlanoContaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using myfinance_web_dotnet.infra;

namespace myfinance_web_dotnet.Models
{
    public class PlanoContaModel
    {   
        public int? Id { get; set; }
        public string? Descricao { get; set; }
        public string? Tipo { get; set; }

        public void Inserir()
        {
            var objDAL = DAL.GetInstancia;
            objDAL.Conectar();
            var sql = $"INSERT INTO PLANO_CONTAS (DESCRICAO, TIPO) VALUES ('{Descricao}','{Tipo}')";
            objDAL.ExecutarComandoSQL(sql);
            objDAL.Desconectar();

        }
        
        public void Atualizar(int? id)
        {
            var objDAL = DAL.GetInstancia;
            objDAL.Conectar();
            var sql = "UPDATE PLANO_CONTAS SET " +
            $"Descricao = '{Descricao}'," +
            $"Tipo = '{Tipo}' " +
            $"WHERE id = {id}";
            objDAL.ExecutarComandoSQL(sql);
            objDAL.Desconectar();
        }
    
        public void Excluir(int id)
        {
            var objDAL = DAL.GetInstancia;
            objDAL.Conectar();
            var sql = $"DELETE FROM PLANO_CONTAS WHERE ID = {id}";
            objDAL.ExecutarComandoSQL(sql);
            objDAL.Desconectar();
        }

        public String TraducaoSaidaTipo()
        {
            if (Tipo.Equals("R"))
            {
                return "Receita";
            }
            else
            {
                return "Despesa";
            }
        }


        public PlanoContaModel CarregarPlanoContaPorId(int? id)
        {

            var objDAL = DAL.GetInstancia;
            objDAL.Conectar();

            var sql = $"SELECT ID, DESCRICAO, TIPO FROM PLANO_CONTAS WHERE ID = {id}";
            var dataTable = objDAL.RetornarDataTable(sql);
            
            var planoConta = new PlanoContaModel()
            {
                Id = int.Parse(dataTable.Rows[0]["ID"].ToString()),
                Descricao = dataTable.Rows[0]["DESCRICAO"].ToString(),
                Tipo = dataTable.Rows[0]["TIPO"].ToString()
            };
             objDAL.Desconectar();
            return planoConta;
        }

        public List<PlanoContaModel> ListaPlanoContas()
        {
            List<PlanoContaModel> lista = new List<PlanoContaModel>();

            var objDAL = DAL.GetInstancia;
            objDAL.Conectar();

            var sql = "SELECT ID, DESCRICAO, TIPO FROM PLANO_CONTAS";
            var dataTable = objDAL.RetornarDataTable(sql);

             for (int i=0; i < dataTable.Rows.Count; i++)
             {
                var planoConta = new PlanoContaModel()
                {
                    Id = int.Parse(dataTable.Rows[i]["ID"].ToString()),
                    Descricao = dataTable.Rows[i]["DESCRICAO"].ToString(),
                    Tipo = dataTable.Rows[i]["TIPO"].ToString()
                };
                lista.Add(planoConta);
             }
             objDAL.Desconectar();
            return lista;
        }
    }
}

myfinance-web-dotnet/Models/TransacaoModel.cs
namespace myfinance_web_dotnet.Models
{
    public class TransacaoModel
    {   
        public int? Id { get; set; }
        public DateTime Data {get; set; }
        public decimal Valor {get; set; }
        public string? Historico { get; set; }
        public string? Tipo { get; set; }
        public int IdPlanoConta {get; set; }
        
    }
}

myfinance-web-dotnet/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myfinance-web-dotnet/Controllers/PlanoContaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using myfinance_web_dotnet.Models;


namespace myfinance_web_dotnet.Controllers
{
    
    public class PlanoContaController : Controller
    {
        private readonly ILogger<PlanoContaController> _logger;

        public PlanoContaController(ILogger<PlanoContaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var planoContasModel = new PlanoContaModel();
            ViewBag.Lista = planoContasModel.ListaPlanoContas();
            return View();
        }

        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id != null)
            {
                var planoConta =  new PlanoContaModel().CarregarPlanoContaPorId(id);
                ViewBag.PlanoConta = planoConta;
            }

            
            return View();
            
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContaModel formulario)
        {
            if (formulario.Id == null)
                formulario.Inserir();
            else
                formulario.Atualizar(formulario.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ExcluirPlanoConta(int id)
        {
           new PlanoContaModel().Excluir(id);
           return RedirectToAction("Index");
        }

    }



}


myfinance-web-dotnet/Controllers/TransacaoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using myfinance_web_dotnet.Domain;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers
{

    public class TransacaoController : Controller
    {
        private readonly ILogger<TransacaoController> _logger;

        public TransacaoController(ILogger<TransacaoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var transacao = new Transacao();
            ViewBag.Lista = transacao.ListaTransacoes();
            return View();
        }

        [HttpGet]
          public IActionResult CriarTransacao( int? id)
        {
            if (id != null)
            {
                var transacao = new Transacao().CarregarTransacaoPorId(id);
                ViewBag.Registro = transacao;
            }

            ViewBag.ListaPlanoContas = new PlanoContaModel().ListaPlanoContas();
            return View();
        }

         [HttpPost]
          public IActionResult CriarTransacao(TransacaoModel formulario)
        {
            var transacao = new Transacao();

            if(formulario.Id == null)
                transacao.Inserir(formulario);
            else
                transacao.Atualizar(formulario);
                
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

myfinance-web-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myfinance-web-dotnet/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContaModel
@{
    ViewData["Title"] = "Plano de Contas";
    var vDescricao = string.Empty;
    var vTipoReceita = "R";
    var vTipoDespesa = "D";

    try{
        vDescricao = @ViewBag.PlanoConta.Descricao;
    }
    catch{}
    
}

<h1>@ViewData["Title"]</h1>
<form asp-controller=PlanoConta asp-action="CriarPlanoConta">

    <input type="hidden" asp-for="Id"><br>
    <label for="fname">Descrição:</label><br>
    <input type="text" asp-for="Descricao" value=@vDescricao><br>

    <label for="lname">Tipo:</label><br>
    <input type="radio" asp-for="Tipo" value=@vTipoReceita>Receita<br>
    <input type="radio" asp-for="Tipo" value=@vTipoDespesa>Despesa<br>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

myfinance-web-dotnet/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Plano Contas";
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<h3>Plano de Contas</h3>
<hr>

<button type="button" class="btn btn-block btn-primary" onclick="CriarPlanoConta()">Criar Plano de Conta</button>

<table class='table table-bordered'>
    <tr>
        <th>#</th>
        <th>#</th>
        <th>Id</th>
        <th>Descricao</th>
        <th>Tipo</th>
    </tr>

    @{
    foreach(var item in (List<PlanoContaModel>)ViewBag.Lista)
    {
        <tr>
            <td><button type="button" class="btn btn-block btn-warning" onclick="EditarPlanoConta(@item.Id.ToString())">Editar</button></td>
            <td>
                <button type="button" class="btn btn-block btn-danger" data-target="#myModal" data-toggle="modal" onclick="EnviarIdExcluir(@item.Id.ToString())">Excluir</button>
            </td>
            <td>@item.Id</td>
            <td>@item.Descricao</td>
            <td>@item.TraducaoSaidaTipo()</td>
        </tr>
    }

    }
</table>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirmação</h4>
            </div>
            <div class="modal-body">


            </div>
            <div class="modal-body">
                Você realmente deseja excluir esse item?
            </div>
            <div class="modal-footer">
                
                <button data-dismiss="modal" type="button" class="btn btn-default">Cancelar</button>
                <button id="botaoDelete" type="button" class="btn btn-primary">Deletar</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<script>

    function CriarPlanoConta() {
        window.location.href = "../PlanoConta/CriarPlanoConta";
    }

    function EditarPlanoConta(id) {
        window.location.href = "../PlanoConta/CriarPlanoConta/" + id;
    }

    function ExcluirPlanoConta(id) {
        const xhttp = new XMLHttpRequest();
        xhttp.open("GET", "../PlanoConta/ExcluirPlanoConta/" + id);
        xhttp.send();

        window.location.reload();
        window.location.reload();
    }

    function EnviarIdExcluir(id) {
        document.getElementById("botaoDelete").setAttribute("onClick", "javascript: ExcluirPlanoConta(" + id + ");");
    }


</script>

myfinance-web-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

myfinance-web-dotnet/Views/Transacao/CriarTransacao.cshtml
@using System.Globalization
@model TransacaoModel
@{
    ViewData["Title"] = "Registro de Transação Financeira";
}
@{
    var vData = "";
    var vDescricao = "";
    var vTipo = "";
    var vValor = "";
    var vId = 0;
    var vPlanoContaId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vData = DateTime.Parse(@ViewBag.Registro.Data.ToString()).toString("yyyy-MM-dd");
        vPlanoContaId = int.Parse(@ViewBag.Registro.IdPlanoConta.ToString());
        vDescricao = @ViewBag.Registro.Historico.ToString();
        vTipo = @ViewBag.Registro.Tipo.ToString();

        CultureInfo invC = CultureInfo.InvariantCulture;
        string value;
        value = @ViewBag.Registro.Valor.ToString(invC);
        vValor = value;
    }

    catch{ }
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Transacao" asp-action="CriarTransacao">
  <input type="hidden" asp-for="Id"/>

  <div class="form-group">
         <label>Data:</label>
         <imput type="date" class="form-control" asp-for="Data" value="@vData">
         <span asp-validation-for="Data" class="text-danger"></span> 
  </div>

  <div class="form-group">
    <label>Tipo:</label>
    @Html.RadioButton("Tipo", "R", new {@class = "form-control"}) Receita <br />
    @Html.RadioButton("Tipo", "D", new {@class = "form-control"}) Despesa <br />
  </div>

  <div class="form-group">
         <label>Valor:</label>
         <imput type="text" class="form-control" asp-for="Valor" step="0.01" value="@vValor">
         <span asp-validation-for="Valor" class="text-danger"></span> 
  </div>

  <div class="form-group">
         <label>Historico: </label>
         @Html.TextArea("Historico",vDescricao, new { @class = "form-control"})
         <span asp-validation-for="Historico" class="text-danger"></span>
  </div>

  <div class="form-group">
         <label> Plano de Contas:</label>
            <select asp-for="IdPlanoConta" class="form-control">
                        @{
                            foreach(var item in (List<PlanoContaModel>)ViewBag.ListaPlanoContas)
                            {
                                    if (item.Id.ToString() == vPlanoContaId.ToString())
                                    {
                                        <option selected value="@item.Id.ToString()">@item.Descricao.ToString()</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Id.ToString()">@item.Descricao.ToString()</option>
                                    }          
                            }
                        }
            </select>
  </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

myfinance-web-dotnet/Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transações";
}

<h3>Transações Financeiras</h3>
<hr>

<button type = "button" class = "btn btn-block btn-primary" onclick="CriarTransacao()">Registrar Transação</button>

<table class='table table-bordered'>
  <tr>
    <th>#</th>
    <th>#</th>
    <th>Id</th>
    <th>Data</th>
    <th>Valor</th>
    <th>Tipo</th>
    <th>Histórico</th>
    <th>Plano de Conta</th>
  </tr>

  @{
    foreach(var item in (List<TransacaoModel>)ViewBag.Lista)
    {
            <tr>
                <td><button type="button" class = "btn btn-block btn-warning" onclick="EditarTransacao(@item.Id.ToString())">Editar</button></td>
                <td><button type="button" class = "btn btn-block btn-danger deleteItem" data-target="#basic" data-toggle="modal" data-path="ExcluirTransacao(@item.Id.ToString())">Excluir</button></td>
                <td>@item.Id</td>
                <td>@item.Data</td>
                <td>@item.Valor</td>
                <td>@item.Tipo</td>
                <td>@item.Historico</td>
                <td>@item.IdPlanoConta</td>
            </tr>
    }

  }
</table>

<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title">Confirmação</h4>
        </div>
        <div class="modal-body">
            Você realmente deseja excluir esse item?
        </div>
        <div class="modal-footer">
            <button data-dismiss="modal" type="button" class="btn btn-default">Cancelar</button>
            <button id="btnContinueDelete" type="button" class="btn btn-primary">Deletar</button>
        </div>
    </div>
</div>

<script>

    var path_to_delete;

    $(".deleteItem").click(function(e) {
        path_to_delete = $(this).data('path');
    });

    $('#btnContinueDelete').click(function () {
        window.location.href = path_to_delete;
    });

    function EditarTransacao(id)
    {
        window.location.href = "../Transacao/CriarTransacao/" + id;
    }

    function RotaExcluirTransacao(id)
    {
        return "../Transacao/ExcluirTransacao/" + id;
    }

         
</script>